sites:
  type: list
  subtype: object
  name: Sites
  description: The websites you want to serve
  default: []
  range: '[0, *)'
  spec:
    type: object
    displayAs: '{{subdomain}}'
    uniqueBy: subdomain
    spec:
      subdomain:
        type: string
        name: Subdomain
        description: The subdomain of your Embassy Pages .onion address to host the website on. For example, a value of "me" would produce a website hosted at http://me.myaddress.onion.
        pattern: '^[a-z-]+$'
        patternDescription: May contain only lowercase characters and hyphens.
        nullable: false
      directory:
        type: string
        name: Directory
        description: The directory in File Browser that contains the static files of your website. For example, a value of "websites/resume_site" would tell Embassy Pages to look for that directory in File Browser.
        pattern: '^(\.|[a-zA-Z0-9_ -][a-zA-Z0-9_ .-]*|([a-zA-Z0-9_ .-][a-zA-Z0-9_ -]+\.*)+)(\/[a-zA-Z0-9_ -][a-zA-Z0-9_ .-]*|\/([a-zA-Z0-9_ .-][a-zA-Z0-9_ -]+\.*)+)*\/?$'
        patternDescription: Must be a valid relative file path
        nullable: false