id = "embassy-pages"
title = "Embassy Pages"
version = "0.1.3"
release-notes = "Upgrade to EmbassyOS v0.3.0"
license = "mit"
wrapper-repo = "https://github.com/Start9Labs/embassy-pages-wrapper"
upstream-repo = "https://github.com/Start9Labs/embassy-pages-wrapper"
support-site = "https://matrix.to/#/!lMnRwPWnyQvOfAoEnD:matrix.start9labs.com?via=matrix.start9labs.com&via=matrix.org&via=hnitbjorg.xyz" 
build = ["make"]
min-os-version = "0.3.0"

[description]
long = "Embassy Pages is a simple web server that uses directories inside File Browser to serve Tor websites."
short = "Create Tor websites, hosted on your Embassy."

[assets]
license = "LICENSE"
icon = "icon.png"
instructions = "instructions.md"
docker-images = "image.tar"

[main]
type = "docker"
image = "main"
entrypoint = "/usr/local/bin/docker_entrypoint.sh"
args = []
mounts = { main = "/root", filebrowser = "/mnt/filebrowser" }
io-format = "yaml"

[health-checks.nginx]
type = "docker"
image = "main"
system = false
entrypoint = "sh"
args = ["-c", "curl http://localhost:80 || exit 1"]
mounts = { main = "/root" }
io-format = "yaml"
critical = false

[config.get]
type = "docker"
image = "compat"
system = true
entrypoint = "compat"
args = ["config", "get", "/root", "/mnt/assets/config_spec.yaml"]
mounts = { compat = "/mnt/assets", main = "/root" }
io-format = "yaml"

[config.set]
type = "docker"
image = "compat"
system = true
entrypoint = "compat"
args = ["config", "set", "embassy-pages", "/root", "/mnt/assets/config_rules.yaml"]
mounts = { compat = "/mnt/assets", main = "/root" }
io-format = "yaml"

[properties]
type = "docker"
image = "compat"
system = true
entrypoint = "compat"
args = ["properties", "/root"]
mounts = { compat = "/mnt/assets", main = "/root" }
io-format = "yaml"

[dependencies.filebrowser]
version = "^2.14.1.1"
description = "Used to upload files to serve."
critical = false
recommended = true

[dependencies.filebrowser.config.check]
type = "docker"
image = "compat"
system = true
entrypoint = "compat"
args = ["dependency", "check", "filebrowser", "/root", "/mnt/assets/filebrowser_config_rules.yaml"]
mounts = { compat = "/mnt/assets", main = "/root" }

[dependencies.filebrowser.config.auto-configure]
type = "docker"
image = "compat"
system = true
entrypoint = "compat"
args = ["dependency", "auto-configure", "filebrowser", "/mnt/assets/filebrowser_config_rules.yaml"]

[volumes.main]
type = "data"

[volumes.filebrowser]
type = "pointer"
package-id = "filebrowser"
volume-id = "main"
path = "/"
readonly = true

[volumes.compat]
type = "assets"

[interfaces.main]
name = "Network interface"
description = "Specifies the interface to listen on for HTTP connections."
tor-config = { port-mapping = { "80" = "80" } }
ui = true
protocols = ["tcp", "http"]

[backup.create]
type = "docker"
image = "compat"
system = true
entrypoint = "compat"
args = ["duplicity", "create", "embassy-pages", "/mnt/backup", "/root"]
mounts = { BACKUP= "/mnt/backup", main= "/root" }

[backup.restore]
type = "docker"
image = "compat"
system = true
entrypoint = "compat"
args = ["duplicity", "restore", "embassy-pages", "/mnt/backup", "/root"]
mounts = { BACKUP= "/mnt/backup", main= "/root" }
