build = ["make"]
id = "embassy-pages"
license = "mit"
release-notes = """
Update backups to use new eOS APIs \
Add Nextcloud as optional dependency \
Add Gitea as optional dependency \
"""
support-site = "https://matrix.to/#/!lMnRwPWnyQvOfAoEnD:matrix.start9labs.com"
title = "Pages"
upstream-repo = "https://github.com/Start9Labs/embassy-pages-wrapper"
version = "0.1.8"
wrapper-repo = "https://github.com/Start9Labs/embassy-pages-wrapper"

[description]
long = "Pages is a simple web server that uses directories inside File Browser to serve Tor websites."
short = "Create Tor websites, hosted on your personal server."

[assets]
icon = "icon.png"
instructions = "instructions.md"
license = "LICENSE"

[main]
args = []
entrypoint = "/usr/local/bin/docker_entrypoint.sh"
image = "main"
io-format = "yaml"
mounts = { main = "/root", filebrowser = "/mnt/filebrowser", nextcloud = "/mnt/nextcloud", gitea = "/mnt/gitea" }
type = "docker"

["health-checks"."web-ui"]
name = "Web UI"
success-message = "Ready to be visited in a web browser"
type = "script"

[config.get]
type = "script"

[config.set]
type = "script"

[properties]
type = "script"

[dependencies.filebrowser]
description = "Used to upload files to serve."
version = "^2.22.4.3"

[dependencies.filebrowser.requirement]
type = "opt-out"
how = "Can alternatively use Nextcloud for file storage"

[dependencies.nextcloud]
description = "Used to upload files to serve."
version = "^25.0.2"

[dependencies.nextcloud.requirement]
type = "opt-in"
how = "Can alternatively use File Browser for file storage"

[dependencies.gitea]
description = "Used to upload files to serve."
version = "^1.16.9.2"

[dependencies.gitea.requirement]
type = "opt-in"
how = "Can be used to host a static website from git repository"

[volumes.main]
type = "data"

[volumes.filebrowser]
package-id = "filebrowser"
path = "data"
readonly = true
type = "pointer"
volume-id = "main"

[volumes.nextcloud]
package-id = "nextcloud"
path = "data/embassy/files"
readonly = true
type = "pointer"
volume-id = "nextcloud"

[volumes.gitea]
package-id = "gitea"
path = "data/git/repositories"
readonly = true
type = "pointer"
volume-id = "gitea"

[interfaces.main]
description = "Your Embassy Pages sites are displayed here when visited in a web browser."
name = "Web UI"
protocols = ["tcp", "http"]
tor-config = { port-mapping = { "80" = "80" } }
ui = true

[backup.create]
type = "script"

[backup.restore]
type = "script"

[migrations.from."*"]
type = "script"
args = [ "from" ]

[migrations.to."*"]
type = "script"
args = [ "to" ]