build = ["make"]
id = "embassy-pages"
license = "mit"
release-notes = """
* Update to run on x86 architecture
* Utilize new eOS APIs
"""
support-site = "https://matrix.to/#/!lMnRwPWnyQvOfAoEnD:matrix.start9labs.com"
title = "Embassy Pages"
upstream-repo = "https://github.com/Start9Labs/embassy-pages-wrapper"
version = "0.1.6"
wrapper-repo = "https://github.com/Start9Labs/embassy-pages-wrapper"

[description]
long = "Embassy Pages is a simple web server that uses directories inside File Browser to serve Tor websites."
short = "Create Tor websites, hosted on your Embassy."

[assets]
icon = "icon.png"
instructions = "instructions.md"
license = "LICENSE"

[main]
type = "script"

[containers.main]
image = "main"

[containers.main.mounts]
main = "/root"
filebrowser = "/mnt/filebrowser"

["health-checks"."web-ui"]
name = "Web UI"
success-message = "Ready to be visited in a web browser"
type = "script"

[config.get]
type = "script"

[config.set]
type = "script"

[properties]
type = "script"

[dependencies.filebrowser]
description = "Used to upload files to serve."
version = "^2.22.4"

[dependencies.filebrowser.requirement]
type = "required"

[volumes.main]
type = "data"

[volumes.filebrowser]
package-id = "filebrowser"
path = "data"
readonly = true
type = "pointer"
volume-id = "main"

[interfaces.main]
description = "Your Embassy Pages sites are displayed here when visited in a web browser."
name = "Web UI"
protocols = ["tcp", "http"]
tor-config = { port-mapping = { "80" = "80" } }
ui = true

[backup.create]
args = ["duplicity", "create", "/mnt/backup", "/root/data"]
entrypoint = "compat"
image = "compat"
io-format = "yaml"
mounts = { BACKUP = "/mnt/backup", main = "/root/data" }
system = true
type = "docker"

[backup.restore]
args = ["duplicity", "restore", "/mnt/backup", "/root/data"]
entrypoint = "compat"
image = "compat"
io-format = "yaml"
mounts = { BACKUP = "/mnt/backup", main = "/root/data" }
system = true
type = "docker"

[migrations.from."*"]
type = "script"
args = [ "from" ]

[migrations.to."*"]
type = "script"
args = [ "to" ]