id = "embassy-pages"
title = "Start9 Pages"
version = "0.1.8"
release-notes = """
Update to latest StartOS APIs
"""
license = "mit"
wrapper-repo = "https://github.com/Start9Labs/embassy-pages-wrapper"
upstream-repo = "https://github.com/Start9Labs/embassy-pages-wrapper"
support-site = "https://matrix.to/#/!lMnRwPWnyQvOfAoEnD:matrix.start9labs.com"
marketing-site = ""

[description]
short = "Create Tor websites, hosted on your personal server."
long = "Start9 Pages is a simple web server that uses folders hosted on other internal services to serve Tor websites."

[assets]
icon = "icon.png"
instructions = "instructions.md"
license = "LICENSE"

[containers.main]
image = "main"
mounts = { main = "/root", filebrowser = "/mnt/filebrowser", nextcloud = "/mnt/nextcloud" }

[volumes.main]
type = "data"

[volumes.filebrowser]
package-id = "filebrowser"
path = "data"
readonly = true
type = "pointer"
volume-id = "main"

[volumes.nextcloud]
package-id = "nextcloud"
path = "data/embassy/files"
readonly = true
type = "pointer"
volume-id = "nextcloud"

[dependencies.filebrowser]
description = "Used to upload files to serve."
version = "^2.22.4"

[dependencies.filebrowser.requirement]
type = "opt-out"
how = "Can alternatively use Nextcloud for file storage"

[dependencies.nextcloud]
description = "Used to upload files to serve."
version = "^25.0.2"

[dependencies.nextcloud.requirement]
type = "opt-in"
how = "Can alternatively use File Browser for file storage"